### ISSUE TITLE
calc_taxes stray ";"

### ISSUE THREAD

**Issue by neovom** [petr-tik/income_calc#11]
There's a stray ";" on line 84 in income_calc.c in calc_taxes. Is the outer foor loop supposed to do nothing? Or are we supposed to execute the inner foor loop for every iteration of the outer for loop?

**Comment by petr-tik** [comment]
I think it is a clang-format bug. If I close the for-loop with a semicolon my emacs clang-on-save hook runs clang-format on the buffer. Clang-format decides to place the semicolon in the middle of a newline
