### ISSUE TITLE
Coding style

### ISSUE THREAD

**Issue by neovom** [petr-tik/income_calc#6]
I'm not sure if there's a coding style applied, but I think it would be good to have one. Doesn't really matter which one, as long as it's applied consistently across all files, but since this is a C project the linux kernel or GNU styles could easily be chosen. The clang format file can be generated with some online tool, for example http://zed0.co.uk/clang-format-configurator/ (there are others as well).

**Comment by petr-tik** [comment]
@bvborisov set up coding style with own .clang-format file. Thanks for the advice
